"""
Public time-of-use tariff rules and charging-price assignment utilities.

The embedded `NATIONAL_TOU_RATES` dictionary digitizes the provincial TOU
schedules used in the analysis. The original policy schedules are public. The
period labels are standardized as:

    deep_valley, valley, shoulder, peak, super_peak

Province and city names are written in English for readability on GitHub.
Input data should use the same English names, or users should map their local
province/city names to these names before running this script.

Expected input:
    data/charging_sessions.csv

Optional input:
    data/tou_rules.json

Main output:
    data/charging_sessions_with_tou_prices.csv
"""

from __future__ import annotations

import json
from datetime import datetime, time
from pathlib import Path
from typing import Any

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"

PERIOD_PRICE_COLUMNS = {
    "deep_valley": "deep_valley_rate",
    "super_peak": "super_peak_rate",
    "peak": "peak_rate",
    "shoulder": "shoulder_rate",
    "valley": "valley_rate",
}

NATIONAL_TOU_RATES: dict[str, Any] = {'Beijing': {'city': 'Beijing',
             'versions': [{'end_ym': '2023-08',
                           'periods': {'summer': {'months': [7, 8],
                                                  'time_slots': {'valley': ['00:00-07:00',
                                                                            '23:00-24:00'],
                                                                 'shoulder': ['07:00-10:00',
                                                                              '15:00-16:00',
                                                                              '17:00-18:00',
                                                                              '21:00-23:00'],
                                                                 'peak': ['10:00-11:00',
                                                                          '13:00-15:00',
                                                                          '18:00-21:00'],
                                                                 'super_peak': ['11:00-13:00',
                                                                                '16:00-17:00']}},
                                       'other_months': {'months': [1, 2, 3, 4, 5, 6, 9, 10, 11, 12],
                                                        'time_slots': {'valley': ['00:00-07:00',
                                                                                  '23:00-24:00'],
                                                                       'shoulder': ['07:00-10:00',
                                                                                    '15:00-18:00',
                                                                                    '21:00-23:00'],
                                                                       'peak': ['10:00-15:00',
                                                                                '18:00-21:00']}}}},
                          {'start_ym': '2023-09',
                           'periods': {'spring_autumn': {'months': [2, 3, 4, 5, 6, 9, 10, 11],
                                                         'time_slots': {'valley': ['00:00-07:00',
                                                                                   '23:00-24:00'],
                                                                        'shoulder': ['07:00-10:00',
                                                                                     '13:00-17:00',
                                                                                     '22:00-23:00'],
                                                                        'peak': ['10:00-13:00',
                                                                                 '17:00-22:00']}},
                                       'summer': {'months': [7, 8],
                                                  'time_slots': {'valley': ['00:00-07:00',
                                                                            '23:00-24:00'],
                                                                 'shoulder': ['07:00-10:00',
                                                                              '13:00-16:00',
                                                                              '22:00-23:00'],
                                                                 'peak': ['10:00-11:00',
                                                                          '17:00-22:00'],
                                                                 'super_peak': ['11:00-13:00',
                                                                                '16:00-17:00']}},
                                       'winter': {'months': [1, 12],
                                                  'time_slots': {'valley': ['00:00-07:00',
                                                                            '23:00-24:00'],
                                                                 'shoulder': ['07:00-10:00',
                                                                              '13:00-17:00',
                                                                              '22:00-23:00'],
                                                                 'peak': ['10:00-13:00',
                                                                          '17:00-18:00',
                                                                          '21:00-22:00'],
                                                                 'super_peak': ['18:00-21:00']}}}}]},
 'Tianjin': {'city': 'Tianjin',
             'periods': {'spring_autumn': {'months': [2, 3, 4, 5, 6, 9, 10, 11],
                                           'time_slots': {'valley': ['00:00-07:00', '23:00-24:00'],
                                                          'shoulder': ['07:00-09:00',
                                                                       '12:00-16:00',
                                                                       '21:00-23:00'],
                                                          'peak': ['09:00-12:00', '16:00-21:00']}},
                         'summer': {'months': [7, 8],
                                    'time_slots': {'valley': ['00:00-07:00', '23:00-24:00'],
                                                   'shoulder': ['07:00-09:00',
                                                                '12:00-16:00',
                                                                '21:00-23:00'],
                                                   'peak': ['09:00-11:00', '17:00-21:00'],
                                                   'super_peak': ['11:00-12:00', '16:00-17:00']}},
                         'winter': {'months': [1, 12],
                                    'time_slots': {'valley': ['00:00-07:00', '23:00-24:00'],
                                                   'shoulder': ['07:00-09:00',
                                                                '12:00-16:00',
                                                                '21:00-23:00'],
                                                   'peak': ['09:00-11:00',
                                                            '16:00-18:00',
                                                            '19:00-21:00'],
                                                   'super_peak': ['11:00-12:00', '18:00-19:00']}}}},
 'Hebei': {'city': 'Hebei',
           'regions': {'region1': {'cities': ['Shijiazhuang',
                                              'Xiongan New Area',
                                              'Handan',
                                              'Xingtai',
                                              'Baoding',
                                              'Cangzhou',
                                              'Hengshui'],
                                   'periods': {'summer': {'months': [6, 7, 8],
                                                          'time_slots': {'valley': ['00:00-08:00'],
                                                                         'shoulder': ['08:00-15:00',
                                                                                      '23:00-24:00'],
                                                                         'peak': ['15:00-19:00',
                                                                                  '22:00-23:00'],
                                                                         'super_peak': ['19:00-22:00']}},
                                               'winter': {'months': [1, 2, 12],
                                                          'time_slots': {'valley': ['01:00-06:00',
                                                                                    '12:00-15:00'],
                                                                         'shoulder': ['00:00-01:00',
                                                                                      '06:00-12:00',
                                                                                      '15:00-16:00'],
                                                                         'peak': ['16:00-17:00',
                                                                                  '19:00-24:00'],
                                                                         'super_peak': ['17:00-19:00']}},
                                               'spring_autumn': {'months': [3, 4, 5, 9, 10, 11],
                                                                 'time_slots': {'valley': ['01:00-06:00',
                                                                                           '12:00-15:00'],
                                                                                'shoulder': ['00:00-01:00',
                                                                                             '06:00-12:00',
                                                                                             '15:00-16:00'],
                                                                                'peak': ['16:00-24:00']}}}},
                       'region2': {'cities': ['Tangshan',
                                              'Zhangjiakou',
                                              'Qinhuangdao',
                                              'Chengde',
                                              'Langfang'],
                                   'periods': {'summer': {'months': [6, 7, 8],
                                                          'time_slots': {'valley': ['00:00-07:00',
                                                                                    '23:00-24:00'],
                                                                         'shoulder': ['07:00-10:00',
                                                                                      '12:00-14:00',
                                                                                      '18:00-19:00',
                                                                                      '21:00-23:00'],
                                                                         'peak': ['11:00-12:00',
                                                                                  '14:00-17:00',
                                                                                  '19:00-20:00'],
                                                                         'super_peak': ['10:00-11:00',
                                                                                        '17:00-18:00',
                                                                                        '20:00-21:00']}},
                                               'winter': {'months': [1, 11, 12],
                                                          'time_slots': {'valley': ['00:00-07:00',
                                                                                    '23:00-24:00'],
                                                                         'shoulder': ['07:00-08:00',
                                                                                      '09:00-10:00',
                                                                                      '11:00-14:00',
                                                                                      '20:00-23:00'],
                                                                         'peak': ['08:00-09:00',
                                                                                  '10:00-11:00',
                                                                                  '14:00-17:00',
                                                                                  '19:00-20:00'],
                                                                         'super_peak': ['17:00-19:00']}},
                                               'spring_autumn': {'months': [2, 3, 4, 5, 9, 10],
                                                                 'time_slots': {'valley': ['00:00-07:00',
                                                                                           '23:00-24:00'],
                                                                                'shoulder': ['07:00-09:00',
                                                                                             '12:00-15:00',
                                                                                             '18:00-19:00',
                                                                                             '21:00-23:00'],
                                                                                'peak': ['09:00-12:00',
                                                                                         '15:00-18:00',
                                                                                         '19:00-21:00']}}}}}},
 'Shanxi': {'city': 'Shanxi',
            'periods': {'spring_autumn': {'months': [2, 3, 4, 5, 6, 9, 10, 11],
                                          'time_slots': {'valley': ['00:00-07:00', '11:00-13:00'],
                                                         'shoulder': ['07:00-08:00',
                                                                      '13:00-17:00',
                                                                      '23:00-24:00'],
                                                         'peak': ['08:00-11:00', '17:00-23:00']}},
                        'peak_months': {'months': [1, 7, 8, 12],
                                        'time_slots': {'valley': ['00:00-07:00', '11:00-13:00'],
                                                       'shoulder': ['07:00-08:00',
                                                                    '13:00-17:00',
                                                                    '23:00-24:00'],
                                                       'peak': ['08:00-11:00',
                                                                '17:00-18:00',
                                                                '20:00-23:00'],
                                                       'super_peak': ['18:00-20:00']}}}},
 'Shandong': {'city': 'Shandong',
              'periods': {'winter': {'months': [1, 12],
                                     'time_slots': {'deep_valley': ['12:00-14:00'],
                                                    'valley': ['10:00-12:00', '14:00-16:00'],
                                                    'shoulder': ['00:00-10:00', '22:00-24:00'],
                                                    'peak': ['16:00-22:00']}},
                          'spring_autumn': {'months': [2, 3, 4, 5],
                                            'time_slots': {'deep_valley': ['11:00-14:00'],
                                                           'valley': ['10:00-11:00', '14:00-15:00'],
                                                           'shoulder': ['00:00-10:00',
                                                                        '15:00-17:00',
                                                                        '22:00-24:00'],
                                                           'peak': ['17:00-22:00']}},
                          'summer': {'months': [6, 7, 8],
                                     'time_slots': {'valley': ['02:00-08:00'],
                                                    'shoulder': ['00:00-02:00',
                                                                 '08:00-16:00',
                                                                 '22:00-24:00'],
                                                    'peak': ['16:00-18:00'],
                                                    'super_peak': ['18:00-22:00']}},
                          'autumn': {'months': [9, 10, 11],
                                     'time_slots': {'deep_valley': ['11:00-14:00'],
                                                    'valley': ['10:00-11:00', '14:00-15:00'],
                                                    'shoulder': ['00:00-10:00',
                                                                 '15:00-16:00',
                                                                 '21:00-24:00'],
                                                    'peak': ['16:00-17:00', '19:00-21:00'],
                                                    'super_peak': ['17:00-19:00']}}}},
 'Shanghai': {'city': 'Shanghai',
              'periods': {'summer': {'months': [7, 8],
                                     'time_slots': {'valley': ['00:00-06:00', '22:00-24:00'],
                                                    'shoulder': ['06:00-08:00',
                                                                 '15:00-18:00',
                                                                 '21:00-22:00'],
                                                    'peak': ['08:00-12:00',
                                                             '14:00-15:00',
                                                             '18:00-21:00'],
                                                    'super_peak': ['12:00-14:00']}},
                          'autumn': {'months': [9],
                                     'time_slots': {'valley': ['00:00-06:00', '22:00-24:00'],
                                                    'shoulder': ['06:00-08:00',
                                                                 '15:00-18:00',
                                                                 '21:00-22:00'],
                                                    'peak': ['08:00-15:00', '18:00-21:00']}},
                          'winter': {'months': [1, 12],
                                     'time_slots': {'valley': ['00:00-06:00', '22:00-24:00'],
                                                    'shoulder': ['06:00-08:00',
                                                                 '11:00-18:00',
                                                                 '21:00-22:00'],
                                                    'peak': ['08:00-11:00', '18:00-19:00'],
                                                    'super_peak': ['19:00-21:00']}},
                          'spring_autumn': {'months': [2, 3, 4, 5, 6, 10, 11],
                                            'time_slots': {'valley': ['00:00-06:00', '22:00-24:00'],
                                                           'shoulder': ['06:00-08:00',
                                                                        '11:00-18:00',
                                                                        '21:00-22:00'],
                                                           'peak': ['08:00-11:00',
                                                                    '18:00-21:00']}}}},
 'Jiangsu': {'city': 'Jiangsu',
             'periods': {'year_round': {'months': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                        'time_slots': {'valley': ['00:00-08:00'],
                                                       'shoulder': ['11:00-17:00', '22:00-24:00'],
                                                       'peak': ['08:00-11:00', '17:00-22:00']}}}},
 'Zhejiang': {'city': 'Zhejiang',
              'versions': [{'end_ym': '2024-02',
                            'periods': {'peak_months': {'months': [1, 7, 8, 12],
                                                        'time_slots': {'valley': ['00:00-08:00',
                                                                                  '11:00-13:00',
                                                                                  '22:00-24:00'],
                                                                       'peak': ['08:00-09:00',
                                                                                '17:00-22:00'],
                                                                       'super_peak': ['09:00-11:00',
                                                                                      '13:00-17:00']}},
                                        'normal_months': {'months': [2, 3, 4, 5, 6, 9, 10, 11],
                                                          'time_slots': {'valley': ['00:00-08:00',
                                                                                    '11:00-13:00',
                                                                                    '22:00-24:00'],
                                                                         'peak': ['08:00-09:00',
                                                                                  '13:00-15:00',
                                                                                  '17:00-22:00'],
                                                                         'super_peak': ['09:00-11:00',
                                                                                        '15:00-17:00']}}}},
                           {'start_ym': '2024-03',
                            'periods': {'spring_autumn': {'months': [2, 3, 4, 5, 6, 9, 10, 11],
                                                          'time_slots': {'valley': ['00:00-08:00',
                                                                                    '11:00-13:00'],
                                                                         'shoulder': ['17:00-24:00'],
                                                                         'peak': ['08:00-11:00',
                                                                                  '13:00-17:00']}},
                                        'summer_winter': {'months': [1, 7, 8, 12],
                                                          'time_slots': {'valley': ['00:00-08:00',
                                                                                    '11:00-13:00'],
                                                                         'shoulder': ['13:00-15:00',
                                                                                      '23:00-24:00'],
                                                                         'peak': ['08:00-09:00',
                                                                                  '17:00-23:00'],
                                                                         'super_peak': ['09:00-11:00',
                                                                                        '15:00-17:00']}}}}]},
 'Anhui': {'city': 'Anhui',
           'versions': [{'end_ym': '2024-03',
                         'periods': {'year_round': {'months': [1,
                                                               2,
                                                               3,
                                                               4,
                                                               5,
                                                               6,
                                                               7,
                                                               8,
                                                               9,
                                                               10,
                                                               11,
                                                               12],
                                                    'time_slots': {'valley': ['00:00-08:00',
                                                                              '23:00-24:00'],
                                                                   'shoulder': ['08:00-09:00',
                                                                                '12:00-17:00',
                                                                                '22:00-23:00'],
                                                                   'peak': ['09:00-12:00',
                                                                            '17:00-22:00']}}}},
                        {'start_ym': '2024-04',
                         'periods': {'summer_autumn': {'months': [7, 8, 9],
                                                       'time_slots': {'valley': ['00:00-09:00'],
                                                                      'shoulder': ['09:00-16:00'],
                                                                      'peak': ['16:00-24:00']}},
                                     'winter': {'months': [1, 12],
                                                'time_slots': {'valley': ['00:00-08:00',
                                                                          '23:00-24:00'],
                                                               'shoulder': ['08:00-15:00'],
                                                               'peak': ['15:00-23:00']}},
                                     'other_months': {'months': [2, 3, 4, 5, 6, 10, 11],
                                                      'time_slots': {'valley': ['00:00-08:00',
                                                                                '23:00-24:00'],
                                                                     'shoulder': ['11:00-16:00',
                                                                                  '21:00-23:00'],
                                                                     'peak': ['08:00-11:00',
                                                                              '16:00-21:00']}}}}]},
 'Fujian': {'city': 'Fujian',
            'versions': [{'end_ym': '2023-12',
                          'periods': {'year_round': {'months': [1,
                                                                2,
                                                                3,
                                                                4,
                                                                5,
                                                                6,
                                                                7,
                                                                8,
                                                                9,
                                                                10,
                                                                11,
                                                                12],
                                                     'time_slots': {'valley': ['00:00-08:00'],
                                                                    'shoulder': ['08:00-10:00',
                                                                                 '12:00-15:00',
                                                                                 '20:00-21:00',
                                                                                 '22:00-24:00'],
                                                                    'peak': ['10:00-11:00',
                                                                             '15:00-17:00',
                                                                             '18:00-20:00',
                                                                             '21:00-22:00'],
                                                                    'super_peak': ['11:00-12:00',
                                                                                   '17:00-18:00']}}}},
                         {'start_ym': '2024-01',
                          'periods': {'summer_autumn': {'months': [7, 8, 9],
                                                        'time_slots': {'valley': ['00:00-08:00'],
                                                                       'shoulder': ['08:00-10:00',
                                                                                    '12:00-15:00',
                                                                                    '20:00-21:00',
                                                                                    '22:00-24:00'],
                                                                       'peak': ['10:00-11:00',
                                                                                '15:00-17:00',
                                                                                '18:00-20:00',
                                                                                '21:00-22:00'],
                                                                       'super_peak': ['11:00-12:00',
                                                                                      '17:00-18:00']}},
                                      'other_months': {'months': [1, 2, 3, 4, 5, 6, 10, 11, 12],
                                                       'time_slots': {'valley': ['00:00-08:00'],
                                                                      'shoulder': ['08:00-10:00',
                                                                                   '12:00-15:00',
                                                                                   '20:00-21:00',
                                                                                   '22:00-24:00'],
                                                                      'peak': ['10:00-12:00',
                                                                               '15:00-20:00',
                                                                               '21:00-22:00']}}}}]},
 'Hubei': {'city': 'Hubei',
           'versions': [{'end_ym': '2024-04',
                         'periods': {'year_round': {'months': [1,
                                                               2,
                                                               3,
                                                               4,
                                                               5,
                                                               6,
                                                               7,
                                                               8,
                                                               9,
                                                               10,
                                                               11,
                                                               12],
                                                    'time_slots': {'valley': ['00:00-07:00',
                                                                              '23:00-24:00'],
                                                                   'shoulder': ['07:00-09:00',
                                                                                '15:00-20:00',
                                                                                '22:00-23:00'],
                                                                   'peak': ['09:00-15:00'],
                                                                   'super_peak': ['20:00-22:00']}}}},
                        {'start_ym': '2024-05',
                         'periods': {'summer': {'months': [7, 8],
                                                'time_slots': {'valley': ['00:00-06:00',
                                                                          '12:00-14:00'],
                                                               'shoulder': ['06:00-12:00',
                                                                            '14:00-16:00'],
                                                               'peak': ['16:00-20:00',
                                                                        '22:00-24:00'],
                                                               'super_peak': ['20:00-22:00']}},
                                     'other_months': {'months': [1, 2, 3, 4, 5, 6, 9, 10, 11, 12],
                                                      'time_slots': {'valley': ['00:00-06:00',
                                                                                '12:00-14:00'],
                                                                     'shoulder': ['06:00-12:00',
                                                                                  '14:00-16:00'],
                                                                     'peak': ['16:00-18:00',
                                                                              '20:00-24:00'],
                                                                     'super_peak': ['18:00-20:00']}}}}]},
 'Hunan': {'city': 'Hunan',
           'versions': [{'periods': {'peak_months': {'months': [1, 7, 8, 9, 12],
                                                     'time_slots': {'valley': ['00:00-07:00',
                                                                               '23:00-24:00'],
                                                                    'shoulder': ['07:00-11:00',
                                                                                 '14:00-18:00'],
                                                                    'peak': ['11:00-14:00',
                                                                             '22:00-23:00'],
                                                                    'super_peak': ['18:00-22:00']}},
                                     'normal_months': {'months': [2, 3, 4, 5, 6, 10, 11],
                                                       'time_slots': {'valley': ['00:00-07:00',
                                                                                 '23:00-24:00'],
                                                                      'shoulder': ['07:00-11:00',
                                                                                   '14:00-18:00'],
                                                                      'peak': ['11:00-14:00',
                                                                               '18:00-23:00']}}}}]},
 'Henan': {'city': 'Henan',
           'versions': [{'end_ym': '2024-05',
                         'periods': {'winter': {'months': [1, 12],
                                                'time_slots': {'valley': ['00:00-07:00',
                                                                          '23:00-24:00'],
                                                               'shoulder': ['07:00-10:00',
                                                                            '14:00-17:00',
                                                                            '21:00-23:00'],
                                                               'peak': ['10:00-14:00',
                                                                        '17:00-18:00',
                                                                        '19:00-21:00'],
                                                               'super_peak': ['18:00-19:00']}},
                                     'summer': {'months': [7, 8],
                                                'time_slots': {'valley': ['00:00-07:00',
                                                                          '23:00-24:00'],
                                                               'shoulder': ['07:00-10:00',
                                                                            '14:00-17:00',
                                                                            '21:00-23:00'],
                                                               'peak': ['10:00-12:00',
                                                                        '17:00-20:00'],
                                                               'super_peak': ['12:00-14:00',
                                                                              '20:00-21:00']}},
                                     'spring_autumn': {'months': [2, 3, 4, 5, 6, 9, 10, 11],
                                                       'time_slots': {'valley': ['00:00-07:00',
                                                                                 '23:00-24:00'],
                                                                      'shoulder': ['07:00-10:00',
                                                                                   '14:00-17:00',
                                                                                   '21:00-23:00'],
                                                                      'peak': ['10:00-14:00',
                                                                               '17:00-21:00']}}}},
                        {'start_ym': '2024-06',
                         'periods': {'jan_dec': {'months': [1, 12],
                                                 'time_slots': {'valley': ['00:00-07:00'],
                                                                'shoulder': ['07:00-16:00'],
                                                                'peak': ['16:00-17:00',
                                                                         '19:00-24:00'],
                                                                'super_peak': ['17:00-19:00']}},
                                     'jul_aug': {'months': [7, 8],
                                                 'time_slots': {'valley': ['00:00-07:00'],
                                                                'shoulder': ['07:00-16:00'],
                                                                'peak': ['16:00-20:00',
                                                                         '23:00-24:00'],
                                                                'super_peak': ['20:00-23:00']}},
                                     'spring_autumn': {'months': [3, 4, 5, 9, 10, 11],
                                                       'time_slots': {'valley': ['00:00-06:00',
                                                                                 '11:00-14:00'],
                                                                      'shoulder': ['06:00-11:00',
                                                                                   '14:00-16:00'],
                                                                      'peak': ['16:00-24:00']}},
                                     'feb_jun': {'months': [2, 6],
                                                 'time_slots': {'valley': ['00:00-07:00'],
                                                                'shoulder': ['07:00-16:00'],
                                                                'peak': ['16:00-24:00']}}}}]},
 'Jiangxi': {'city': 'Jiangxi',
             'versions': [{'end_ym': '2024-04',
                           'periods': {'summer': {'months': [7, 8, 9],
                                                  'time_slots': {'valley': ['00:00-06:00'],
                                                                 'shoulder': ['06:00-16:00',
                                                                              '22:00-24:00'],
                                                                 'peak': ['16:00-20:00'],
                                                                 'super_peak': ['20:00-22:00']}},
                                       'winter': {'months': [1, 12],
                                                  'time_slots': {'valley': ['00:00-06:00'],
                                                                 'shoulder': ['06:00-09:00',
                                                                              '12:00-17:00',
                                                                              '20:00-24:00'],
                                                                 'peak': ['09:00-12:00',
                                                                          '19:00-20:00'],
                                                                 'super_peak': ['17:00-19:00']}},
                                       'spring_autumn': {'months': [2, 3, 4, 5, 6, 10, 11],
                                                         'time_slots': {'valley': ['00:00-06:00'],
                                                                        'shoulder': ['06:00-16:00',
                                                                                     '22:00-24:00'],
                                                                        'peak': ['16:00-22:00']}}}},
                          {'start_ym': '2024-05',
                           'periods': {'summer': {'months': [7, 8, 9],
                                                  'time_slots': {'valley': ['00:00-06:00'],
                                                                 'shoulder': ['06:00-16:30',
                                                                              '22:30-24:00'],
                                                                 'peak': ['16:30-20:30'],
                                                                 'super_peak': ['20:30-22:30']}},
                                       'winter': {'months': [1, 12],
                                                  'time_slots': {'valley': ['00:00-06:00'],
                                                                 'shoulder': ['06:00-08:30',
                                                                              '11:30-18:00',
                                                                              '21:00-24:00'],
                                                                 'peak': ['08:30-11:30',
                                                                          '20:00-21:00'],
                                                                 'super_peak': ['18:00-20:00']}},
                                       'spring_autumn': {'months': [2, 3, 4, 5, 6, 10, 11],
                                                         'time_slots': {'valley': ['00:00-06:00'],
                                                                        'shoulder': ['06:00-16:00',
                                                                                     '22:00-24:00'],
                                                                        'peak': ['16:00-22:00']}}}}]},
 'Sichuan': {'city': 'Sichuan',
             'versions': [{'end_ym': '2023-05',
                           'periods': {'year_round': {'months': [1,
                                                                 2,
                                                                 3,
                                                                 4,
                                                                 5,
                                                                 6,
                                                                 7,
                                                                 8,
                                                                 9,
                                                                 10,
                                                                 11,
                                                                 12],
                                                      'time_slots': {'valley': ['00:00-07:00',
                                                                                '23:00-24:00'],
                                                                     'shoulder': ['07:00-11:00',
                                                                                  '12:00-14:00',
                                                                                  '21:00-23:00'],
                                                                     'peak': ['11:00-12:00',
                                                                              '14:00-21:00']}}}},
                          {'start_ym': '2023-06',
                           'periods': {'summer': {'months': [7, 8],
                                                  'time_slots': {'valley': ['00:00-07:00',
                                                                            '23:00-24:00'],
                                                                 'shoulder': ['07:00-10:00',
                                                                              '12:00-15:00',
                                                                              '21:00-23:00'],
                                                                 'peak': ['10:00-12:00',
                                                                          '17:00-21:00'],
                                                                 'super_peak': ['15:00-17:00']}},
                                       'winter': {'months': [1, 12],
                                                  'time_slots': {'valley': ['00:00-07:00',
                                                                            '23:00-24:00'],
                                                                 'shoulder': ['07:00-10:00',
                                                                              '12:00-15:00',
                                                                              '21:00-23:00'],
                                                                 'peak': ['10:00-12:00',
                                                                          '15:00-19:00'],
                                                                 'super_peak': ['19:00-21:00']}},
                                       'spring_autumn': {'months': [2, 3, 4, 5, 6, 9, 10, 11],
                                                         'time_slots': {'valley': ['00:00-07:00',
                                                                                   '23:00-24:00'],
                                                                        'shoulder': ['07:00-10:00',
                                                                                     '12:00-15:00',
                                                                                     '21:00-23:00'],
                                                                        'peak': ['10:00-12:00',
                                                                                 '15:00-21:00']}}}}]},
 'Chongqing': {'city': 'Chongqing',
               'periods': {'peak_months': {'months': [1, 7, 8, 12],
                                           'time_slots': {'valley': ['00:00-08:00'],
                                                          'shoulder': ['08:00-11:00',
                                                                       '17:00-20:00',
                                                                       '22:00-24:00'],
                                                          'peak': ['11:00-12:00',
                                                                   '14:00-17:00',
                                                                   '20:00-22:00'],
                                                          'super_peak': ['12:00-14:00']}},
                           'normal_months': {'months': [2, 3, 4, 5, 6, 9, 10, 11],
                                             'time_slots': {'valley': ['00:00-08:00'],
                                                            'shoulder': ['08:00-11:00',
                                                                         '17:00-20:00',
                                                                         '22:00-24:00'],
                                                            'peak': ['11:00-17:00',
                                                                     '20:00-22:00']}}}},
 'Liaoning': {'city': 'Liaoning',
              'periods': {'peak_months': {'months': [1, 7, 8, 12],
                                          'time_slots': {'valley': ['00:00-05:00',
                                                                    '11:30-12:30',
                                                                    '22:00-24:00'],
                                                         'shoulder': ['05:00-07:30',
                                                                      '10:30-11:30',
                                                                      '12:30-16:00',
                                                                      '21:00-22:00'],
                                                         'peak': ['07:30-10:30',
                                                                  '16:00-17:00',
                                                                  '19:00-21:00'],
                                                         'super_peak': ['17:00-19:00']}},
                          'normal_months': {'months': [2, 3, 4, 5, 6, 9, 10, 11],
                                            'time_slots': {'valley': ['00:00-05:00',
                                                                      '11:30-12:30',
                                                                      '22:00-24:00'],
                                                           'shoulder': ['05:00-07:30',
                                                                        '10:30-11:30',
                                                                        '12:30-16:00',
                                                                        '21:00-22:00'],
                                                           'peak': ['07:30-10:30',
                                                                    '16:00-21:00']}}}},
 'Jilin': {'city': 'Jilin',
           'periods': {'peak_months': {'months': [1, 2, 7, 8, 11, 12],
                                       'time_slots': {'valley': ['00:00-06:00', '23:00-24:00'],
                                                      'shoulder': ['06:00-09:00',
                                                                   '11:30-15:30',
                                                                   '21:00-23:00'],
                                                      'peak': ['09:00-11:30',
                                                               '15:30-16:00',
                                                               '18:00-21:00'],
                                                      'super_peak': ['16:00-18:00']}},
                       'normal_months': {'months': [3, 4, 5, 6, 9, 10],
                                         'time_slots': {'valley': ['00:00-06:00', '23:00-24:00'],
                                                        'shoulder': ['06:00-09:00',
                                                                     '11:30-15:30',
                                                                     '21:00-23:00'],
                                                        'peak': ['09:00-11:30', '15:30-21:00']}}}},
 'Heilongjiang': {'city': 'Heilongjiang',
                  'periods': {'peak_months': {'months': [1, 7, 8, 9, 11, 12],
                                              'time_slots': {'valley': ['00:00-05:30',
                                                                        '22:30-24:00'],
                                                             'shoulder': ['05:30-06:00',
                                                                          '07:00-09:00',
                                                                          '11:30-15:30',
                                                                          '20:00-22:30'],
                                                             'peak': ['06:00-07:00',
                                                                      '09:00-11:30',
                                                                      '15:30-16:30',
                                                                      '18:30-20:00'],
                                                             'super_peak': ['16:30-18:30']}},
                              'normal_months': {'months': [2, 3, 4, 5, 6, 10],
                                                'time_slots': {'valley': ['00:00-05:30',
                                                                          '22:30-24:00'],
                                                               'shoulder': ['05:30-06:00',
                                                                            '07:00-09:00',
                                                                            '11:30-15:30',
                                                                            '20:00-22:30'],
                                                               'peak': ['06:00-07:00',
                                                                        '09:00-11:30',
                                                                        '15:30-20:00']}}}},
 'Inner Mongolia': {'city': 'Inner Mongolia',
                    'regions': {'region1': {'cities': ['Hulunbuir',
                                                       'Hinggan League',
                                                       'Tongliao',
                                                       'Chifeng',
                                                       'Manzhouli'],
                                            'periods': {'summer': {'months': [6, 7, 8],
                                                                   'time_slots': {'valley': ['00:00-05:00',
                                                                                             '22:00-24:00'],
                                                                                  'shoulder': ['05:00-07:30',
                                                                                               '11:30-17:00',
                                                                                               '21:00-22:00'],
                                                                                  'peak': ['07:30-11:30',
                                                                                           '17:00-18:00',
                                                                                           '20:00-21:00'],
                                                                                  'super_peak': ['18:00-20:00']}},
                                                        'other_months': {'months': [1,
                                                                                    2,
                                                                                    3,
                                                                                    4,
                                                                                    5,
                                                                                    9,
                                                                                    10,
                                                                                    11,
                                                                                    12],
                                                                         'time_slots': {'valley': ['00:00-05:00',
                                                                                                   '22:00-24:00'],
                                                                                        'shoulder': ['05:00-07:30',
                                                                                                     '11:30-17:00',
                                                                                                     '21:00-22:00'],
                                                                                        'peak': ['07:30-11:30',
                                                                                                 '17:00-21:00']}}}},
                                'region2': {'cities': ['Hohhot',
                                                       'Baotou',
                                                       'Xilingol League',
                                                       'Ulanqab',
                                                       'Ordos',
                                                       'Bayannur',
                                                       'Wuhai',
                                                       'Alxa League',
                                                       'Erenhot'],
                                            'periods': {'small_wind_season': {'months': [6, 7, 8],
                                                                              'time_slots': {'valley': ['10:00-15:00'],
                                                                                             'shoulder': ['00:00-05:00',
                                                                                                          '07:00-10:00',
                                                                                                          '15:00-17:00',
                                                                                                          '21:00-24:00'],
                                                                                             'peak': ['05:00-07:00',
                                                                                                      '17:00-21:00']}},
                                                        'big_wind_season': {'months': [1,
                                                                                       2,
                                                                                       3,
                                                                                       4,
                                                                                       5,
                                                                                       9,
                                                                                       10,
                                                                                       11,
                                                                                       12],
                                                                            'time_slots': {'valley': ['00:00-04:00',
                                                                                                      '10:00-15:00'],
                                                                                           'shoulder': ['04:00-10:00',
                                                                                                        '15:00-17:00',
                                                                                                        '21:00-24:00'],
                                                                                           'peak': ['17:00-21:00']}}}}}},
 'Shaanxi': {'city': 'Shaanxi',
             'periods': {'winter': {'months': [1, 12],
                                    'time_slots': {'valley': ['00:00-07:00', '23:00-24:00'],
                                                   'shoulder': ['07:00-08:00', '11:30-18:30'],
                                                   'peak': ['08:00-11:30', '20:30-23:00'],
                                                   'super_peak': ['18:30-20:30']}},
                         'summer': {'months': [7, 8],
                                    'time_slots': {'valley': ['00:00-07:00', '23:00-24:00'],
                                                   'shoulder': ['07:00-08:00', '11:30-18:30'],
                                                   'peak': ['08:00-11:30',
                                                            '18:30-19:30',
                                                            '21:30-23:00'],
                                                   'super_peak': ['19:30-21:30']}},
                         'spring_autumn': {'months': [2, 3, 4, 5, 6, 9, 10, 11],
                                           'time_slots': {'valley': ['00:00-07:00', '23:00-24:00'],
                                                          'shoulder': ['07:00-08:00',
                                                                       '11:30-18:30'],
                                                          'peak': ['08:00-11:30',
                                                                   '18:30-23:00']}}}},
 'Gansu': {'city': 'Gansu',
           'periods': {'year_round': {'months': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                      'time_slots': {'shoulder': ['00:00-07:00', '23:00-24:00'],
                                                     'peak': ['07:00-09:00', '17:00-23:00'],
                                                     'valley': ['09:00-17:00']}}}},
 'Qinghai': {'city': 'Qinghai',
             'periods': {'peak_months': {'months': [1, 2, 3, 10, 11, 12],
                                         'time_slots': {'valley': ['00:00-08:00'],
                                                        'shoulder': ['11:00-18:00', '23:00-24:00'],
                                                        'peak': ['09:00-11:00',
                                                                 '18:00-19:00',
                                                                 '21:00-23:00'],
                                                        'super_peak': ['08:00-09:00',
                                                                       '19:00-21:00']}},
                         'normal_months': {'months': [4, 5, 6, 7, 8, 9],
                                           'time_slots': {'valley': ['00:00-08:00'],
                                                          'shoulder': ['11:00-18:00',
                                                                       '23:00-24:00'],
                                                          'peak': ['08:00-11:00',
                                                                   '18:00-23:00']}}}},
 'Ningxia': {'city': 'Ningxia',
             'periods': {'year_round': {'months': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                        'time_slots': {'shoulder': ['00:00-07:00', '23:00-24:00'],
                                                       'peak': ['07:00-09:00', '17:00-23:00'],
                                                       'valley': ['09:00-17:00']}}}},
 'Xinjiang': {'city': 'Xinjiang',
              'periods': {'winter': {'months': [1, 11, 12],
                                     'time_slots': {'shoulder': ['00:00-04:00',
                                                                 '11:00-13:00',
                                                                 '17:00-19:00'],
                                                    'valley': ['04:00-08:00', '13:00-17:00'],
                                                    'peak': ['08:00-11:00', '21:00-24:00'],
                                                    'super_peak': ['19:00-21:00']}},
                          'summer': {'months': [7],
                                     'time_slots': {'shoulder': ['00:00-04:00',
                                                                 '11:00-13:00',
                                                                 '17:00-19:00'],
                                                    'valley': ['04:00-08:00',
                                                               '13:00-14:00',
                                                               '16:00-17:00'],
                                                    'deep_valley': ['14:00-16:00'],
                                                    'peak': ['08:00-11:00',
                                                             '19:00-21:00',
                                                             '23:00-24:00'],
                                                    'super_peak': ['21:00-23:00']}},
                          'late_spring_early_autumn': {'months': [5, 6, 8],
                                                       'time_slots': {'shoulder': ['00:00-04:00',
                                                                                   '11:00-13:00',
                                                                                   '17:00-19:00'],
                                                                      'valley': ['04:00-08:00',
                                                                                 '13:00-14:00',
                                                                                 '16:00-17:00'],
                                                                      'peak': ['08:00-11:00',
                                                                               '19:00-24:00'],
                                                                      'deep_valley': ['14:00-16:00']}},
                          'spring_autumn': {'months': [2, 3, 4, 9, 10],
                                            'time_slots': {'shoulder': ['00:00-04:00',
                                                                        '11:00-13:00',
                                                                        '17:00-19:00'],
                                                           'valley': ['04:00-08:00', '13:00-17:00'],
                                                           'peak': ['08:00-11:00',
                                                                    '19:00-24:00']}}}},
 'Tibet': {'city': 'Tibet',
           'periods': {'year_round': {'months': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                      'time_slots': {'shoulder': ['00:00-10:00'],
                                                     'valley': ['10:00-17:00'],
                                                     'peak': ['17:00-24:00']}}}},
 'Yunnan': {'city': 'Yunnan',
            'versions': [{'end_ym': '2023-12',
                          'periods': {'peak_months': {'months': [1, 5, 11, 12],
                                                      'time_slots': {'valley': ['00:00-07:00',
                                                                                '23:00-24:00'],
                                                                     'shoulder': ['07:00-09:00',
                                                                                  '12:00-18:00'],
                                                                     'peak': ['09:00-10:30',
                                                                              '11:30-12:00',
                                                                              '19:00-23:00'],
                                                                     'super_peak': ['10:30-11:30',
                                                                                    '18:00-19:00']}},
                                      'normal_months': {'months': [2, 3, 4, 6, 7, 8, 9, 10],
                                                        'time_slots': {'valley': ['00:00-07:00',
                                                                                  '23:00-24:00'],
                                                                       'shoulder': ['07:00-09:00',
                                                                                    '12:00-18:00'],
                                                                       'peak': ['09:00-12:00',
                                                                                '18:00-23:00']}}}},
                         {'start_ym': '2024-01',
                          'periods': {'peak_months': {'months': [1, 3, 4, 12],
                                                      'time_slots': {'valley': ['00:00-07:00',
                                                                                '23:00-24:00'],
                                                                     'shoulder': ['07:00-09:00',
                                                                                  '12:00-17:00',
                                                                                  '22:00-23:00'],
                                                                     'peak': ['09:00-10:30',
                                                                              '11:30-12:00',
                                                                              '17:00-17:30',
                                                                              '18:30-22:00'],
                                                                     'super_peak': ['10:30-11:30',
                                                                                    '17:30-18:30']}},
                                      'normal_months': {'months': [2, 5, 6, 7, 8, 9, 10, 11],
                                                        'time_slots': {'valley': ['00:00-07:00',
                                                                                  '23:00-24:00'],
                                                                       'shoulder': ['07:00-09:00',
                                                                                    '12:00-17:00',
                                                                                    '22:00-23:00'],
                                                                       'peak': ['09:00-12:00',
                                                                                '17:00-22:00']}}}}]},
 'Guangdong': {'city': 'Guangdong',
               'periods': {'normal_months': {'months': [1, 2, 3, 4, 5, 6, 10, 11, 12],
                                             'time_slots': {'valley': ['00:00-08:00'],
                                                            'shoulder': ['08:00-10:00',
                                                                         '12:00-14:00',
                                                                         '19:00-24:00'],
                                                            'peak': ['10:00-12:00',
                                                                     '14:00-19:00']}},
                           'summer_peak': {'months': [7, 8, 9],
                                           'time_slots': {'valley': ['00:00-08:00'],
                                                          'shoulder': ['08:00-10:00',
                                                                       '12:00-14:00',
                                                                       '19:00-24:00'],
                                                          'peak': ['10:00-11:00',
                                                                   '14:00-15:00',
                                                                   '17:00-19:00'],
                                                          'super_peak': ['11:00-12:00',
                                                                         '15:00-17:00']}}}},
 'Guangxi': {'city': 'Guangxi',
             'versions': [{'end_ym': '2023-08',
                           'periods': {'year_round': {'months': [1,
                                                                 2,
                                                                 3,
                                                                 4,
                                                                 5,
                                                                 6,
                                                                 7,
                                                                 8,
                                                                 9,
                                                                 10,
                                                                 11,
                                                                 12],
                                                      'time_slots': {'valley': ['00:00-06:00'],
                                                                     'shoulder': ['06:00-10:00',
                                                                                  '16:00-24:00'],
                                                                     'peak': ['10:00-16:00']}}}},
                          {'start_ym': '2023-09',
                           'periods': {'year_round': {'months': [1,
                                                                 2,
                                                                 3,
                                                                 4,
                                                                 5,
                                                                 6,
                                                                 7,
                                                                 8,
                                                                 9,
                                                                 10,
                                                                 11,
                                                                 12],
                                                      'time_slots': {'valley': ['00:00-07:00',
                                                                                '23:00-24:00'],
                                                                     'shoulder': ['07:00-11:00',
                                                                                  '13:00-17:00'],
                                                                     'peak': ['11:00-13:00',
                                                                              '17:00-23:00']}}}}]},
 'Hainan': {'city': 'Hainan',
            'periods': {'year_round': {'months': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                                       'time_slots': {'shoulder': ['08:00-16:00'],
                                                      'valley': ['00:00-08:00'],
                                                      'peak': ['16:00-24:00']}}}},
 'Guizhou': {'city': 'Guizhou',
             'versions': [{'end_ym': '2023-07',
                           'periods': {'year_round': {'months': [1,
                                                                 2,
                                                                 3,
                                                                 4,
                                                                 5,
                                                                 6,
                                                                 7,
                                                                 8,
                                                                 9,
                                                                 10,
                                                                 11,
                                                                 12],
                                                      'time_slots': {'valley': ['00:00-07:00',
                                                                                '23:00-24:00'],
                                                                     'shoulder': ['07:00-09:00',
                                                                                  '12:00-16:00',
                                                                                  '21:00-23:00'],
                                                                     'peak': ['09:00-12:00',
                                                                              '16:00-21:00']}}}},
                          {'start_ym': '2023-08',
                           'periods': {'year_round': {'months': [1,
                                                                 2,
                                                                 3,
                                                                 4,
                                                                 5,
                                                                 6,
                                                                 7,
                                                                 8,
                                                                 9,
                                                                 10,
                                                                 11,
                                                                 12],
                                                      'time_slots': {'valley': ['00:00-08:00'],
                                                                     'shoulder': ['08:00-10:00',
                                                                                  '13:00-17:00',
                                                                                  '22:00-24:00'],
                                                                     'peak': ['10:00-13:00',
                                                                              '17:00-22:00']}}}}]}}


def parse_clock(value: str) -> time:
    """Parse a clock string such as `08:30` or `24:00`."""
    if value in {"24:00", "24:00:00"}:
        return time(23, 59, 59)
    return datetime.strptime(value, "%H:%M").time()


def clock_in_range(clock: time, start: time, end: time) -> bool:
    """Return whether `clock` falls in a time interval, including overnight intervals."""
    if start <= end:
        return start <= clock < end
    return clock >= start or clock < end


def year_month(timestamp: str) -> str:
    return pd.to_datetime(timestamp).strftime("%Y-%m")


def month_number(timestamp: str) -> int:
    return int(pd.to_datetime(timestamp).month)


def version_applies(version: dict[str, Any], ym: str) -> bool:
    start_ym = version.get("start_ym")
    end_ym = version.get("end_ym")
    if start_ym is not None and ym < start_ym:
        return False
    if end_ym is not None and ym > end_ym:
        return False
    return True


def select_regional_rule(province_rule: dict[str, Any], city: str | None) -> dict[str, Any]:
    """Select city-specific regional rules when a province has sub-regions."""
    regions = province_rule.get("regions")
    if not regions:
        return province_rule
    if city is None or pd.isna(city):
        raise ValueError("City is required for provinces with regional TOU rules.")

    for region_rule in regions.values():
        cities = region_rule.get("cities", [])
        if city in cities:
            return region_rule
    raise ValueError(f"City not found in regional TOU rules: {city}")


def select_version(rule: dict[str, Any], ym: str) -> dict[str, Any]:
    versions = rule.get("versions")
    if versions is None:
        return rule

    for version in versions:
        if version_applies(version, ym):
            return version
    raise ValueError(f"No applicable tariff version for year-month {ym}.")


def select_season(version: dict[str, Any], month: int) -> dict[str, Any]:
    for season_rule in version["periods"].values():
        if month in season_rule["months"]:
            return season_rule
    raise ValueError(f"No applicable seasonal tariff rule for month {month}.")


def period_for_clock(season_rule: dict[str, Any], clock: time) -> str:
    for period, intervals in season_rule["time_slots"].items():
        for interval in intervals:
            start_str, end_str = interval.split("-")
            if clock_in_range(clock, parse_clock(start_str), parse_clock(end_str)):
                return period
    raise ValueError(f"No TOU period found for clock time {clock}.")


def load_tariff_rules(path: Path | None = None) -> dict[str, Any]:
    """Load tariff rules from JSON if available; otherwise use embedded public rules."""
    rules_path = path or DATA / "tou_rules.json"
    if rules_path.exists():
        with rules_path.open("r", encoding="utf-8") as file:
            return json.load(file)
    return NATIONAL_TOU_RATES


def assign_tou_period(row: pd.Series, rules: dict[str, Any]) -> str:
    province = row["province"]
    city = row.get("city")
    begin_time = row["begin_time"]

    if province not in rules:
        raise KeyError(f"Province not found in TOU rules: {province}")

    ym = year_month(begin_time)
    month = month_number(begin_time)
    clock = pd.to_datetime(begin_time).time()

    province_rule = select_regional_rule(rules[province], city)
    version = select_version(province_rule, ym)
    season_rule = select_season(version, month)
    return period_for_clock(season_rule, clock)


def assign_expected_price(row: pd.Series) -> float:
    price_column = PERIOD_PRICE_COLUMNS[row["tou_period"]]
    return float(row[price_column])


def main() -> None:
    sessions_path = DATA / "charging_sessions.csv"
    output_path = DATA / "charging_sessions_with_tou_prices.csv"

    sessions = pd.read_csv(sessions_path)
    rules = load_tariff_rules()

    sessions["tou_period"] = sessions.apply(assign_tou_period, axis=1, rules=rules)
    sessions["expected_price"] = sessions.apply(assign_expected_price, axis=1)
    sessions.to_csv(output_path, index=False)


if __name__ == "__main__":
    main()
